### ISSUE TITLE
Does it work with python 3.11 or not? Help me

### ISSUE THREAD

**Issue by OdarShan** [Cobertos/md2notion#65]
Traceback (most recent call last):
  File "c:\Users\OD\3D Objects\Programas\Notion_Import\fromnotion.py", line 6, in <module>
    client = NotionClient(token_v2="<erased>")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OD\AppData\Local\Programs\Python\Python311\Lib\site-packages\notion\client.py", line 77, in __init__     
    self.session = create_session(client_specified_retry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OD\AppData\Local\Programs\Python\Python311\Lib\site-packages\notion\client.py", line 39, in create_session
    retry = Retry(
            ^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'
PS C:\Users\OD\3D Objects\Programas\Notion_Import>

**Comment by SHEN-Muchuan** [comment]
I have the same problem with both 3.6.x and 3.11.x

**Comment by Jinxuyang** [comment]
Try to install requests 2.29.0
`pip install requests==2.29.0`
